version: '3.9'


services:
  flask:
    container_name: flask
    build:
      dockerfile: flask_blog_app/Dockerfile
      context: ./flask_blog_app
    ports:
      - '5000:5000'
    command: python3 ./flask_blog_app/app.py

